// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-URERIGo20kRtOcbFWhQtmdkDgrj_OUs',
    appId: '1:239617450433:web:751b4ebb59ee665b77cf40',
    messagingSenderId: '239617450433',
    projectId: 'tiktok-data-9eb93',
    authDomain: 'tiktok-data-9eb93.firebaseapp.com',
    storageBucket: 'tiktok-data-9eb93.appspot.com',
    measurementId: 'G-E0KEWBKFSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4S3q14GoRs6LWXuGyJ4jShlWopA5rsrw',
    appId: '1:239617450433:android:c43a2ebd6243757877cf40',
    messagingSenderId: '239617450433',
    projectId: 'tiktok-data-9eb93',
    storageBucket: 'tiktok-data-9eb93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKkZjJ0BeAizLRnI8Eyle-C10wUeveQK8',
    appId: '1:239617450433:ios:63d6653b6ce4bb0677cf40',
    messagingSenderId: '239617450433',
    projectId: 'tiktok-data-9eb93',
    storageBucket: 'tiktok-data-9eb93.appspot.com',
    iosBundleId: 'com.example.toptop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKkZjJ0BeAizLRnI8Eyle-C10wUeveQK8',
    appId: '1:239617450433:ios:e6c7e37a7f18aa6a77cf40',
    messagingSenderId: '239617450433',
    projectId: 'tiktok-data-9eb93',
    storageBucket: 'tiktok-data-9eb93.appspot.com',
    iosBundleId: 'com.example.toptop.RunnerTests',
  );
}
